### PR TITLE
feat: updated ckeditor and added code blocks

### PR DESCRIPTION
**Pull request by wakonig**

### CODE REVIEW

**Comment by stephan271** [comment]
Yes, I agree. I don think code block support is super urgent.

**Review by stephan271 — APPROVED** [review]

**Comment by minottic** [comment]
@wakonig so you mentioned earlier that this is now ready to go?

**Comment by wakonig** [comment]
FE should be fine but could you have a look at the exported pdf? Would be great if we could add the syntax highlighting also to the exported pdf.

**Comment by minottic** [comment]
the pdf export indeed misses the syntax highlighting but keeps the formatting. So I would say we can start merging this feature and after that I will add prismjs sytnax highlighting in the pdf

**Pull request merged**
